### PR TITLE
Integration with pyscript.com

### PR DESCRIPTION
**Pull request by ntoll**
**DO NOT MERGE** this is a work in progress.

- [x] Figure out how Typer works / is tested
- [x] Add `new` command to create skeleton pyscript project.
- [x] Interactive project creation resulting in a `manifest.toml` file for project metadata.
- [x] Tests for all the above.

### CODE REVIEW

**Comment by marimeireles** [comment]
Wooh, cheers for setting this up!! ✨

**Comment by marimeireles** [comment]
Should I help here? 🤔
Can take over, I saw on Slack that you're up to other things.

**Comment by mattkram** [comment]
@marimeireles I'm monitoring this. But also, definitely happy for help! This is definitely a tool that, although I kicked it off, will become more important over time to have core support or at least knowledge.

Right now this particular PR is still draft, but definitely feel free to shoot any questions my way if you have them 🙂

**Comment by ntoll** [comment]
This work will happen elsewhere as a plugin to complement the `pyscript` CLI.

**Pull request closed without merging**
